### PR TITLE
ADD: initial unittest for agentneo.py file

### PR DESCRIPTION
**Pull request by 01PrathamS**
## Description
- Initial commit for unit tests in `AgentNeo/agentneo.py`.
- Adds tests for project creation, project connection, project listing, and dashboard launch functionalities.
- Updated `requirements.txt` with `pytest` for testing support.

## Related Issue
-  #3 (Add Unit Tests)

## Type of Change
- [x] Added unit tests for `AgentNeo/agentneo.py` functionalities.
- [x] Updated `requirements.txt` with `pytest`.

## How Has This Been Tested?
- Ran the new test cases to verify successful creation, connection, and listing of projects.
- Ensured tests handle cases where projects already exist without causing test failures.
- Verified the dashboard launch functionality with `mock`.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, especially in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my feature works as expected.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Context
- Exception handling in tests ensures cases with pre-existing projects are managed without needing deletion.
- Sample test output and debugging information available upon request.

## Impact on Roadmap
- Aligns with project goals to improve code reliability and maintainability through comprehensive testing.
- Supports future feature integration by ensuring foundational tests are in place.

### CODE REVIEW

**Comment by 01PrathamS** [comment]
can you please review this @kiranscaria, help me over here if things need to be refactored Thanks!!

**Review by kiranscaria — CHANGES_REQUESTED** [review]
@01PrathamS The changes seem okay, but pls re-raise the PR against this branch: https://github.com/raga-ai-hub/AgentNeo/tree/v1.2

**Comment by 01PrathamS** [comment]
@kiranscaria does this works?

**Comment by kiranscaria** [comment]
@01PrathamS You will need to close this PR and raise a new PR against this branch: https://github.com/raga-ai-hub/AgentNeo/tree/v1.2

**Pull request closed without merging**
